// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfZ-yzVxm0OpYCf0kBSMMb7C5EGvntSRk',
    appId: '1:605653696899:android:637f28673b00c57a15f6b6',
    messagingSenderId: '605653696899',
    projectId: 'clocklify-kent',
    databaseURL: 'https://clocklify-kent-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'clocklify-kent.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEoWcIoTQWDFwPJP1gzxVGwmc_fHaYgp0',
    appId: '1:605653696899:ios:a969c26044e576a515f6b6',
    messagingSenderId: '605653696899',
    projectId: 'clocklify-kent',
    databaseURL: 'https://clocklify-kent-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'clocklify-kent.appspot.com',
    iosClientId: '605653696899-bp97htddhsst32ejlssr10e1ldg7o1me.apps.googleusercontent.com',
    iosBundleId: 'com.example.clockifyKent',
  );
}
