name: clockify_kent
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.13
  permission_handler: ^9.2.0
  file_picker: ^4.5.1
  provider: ^6.0.0
  geolocator: ^9.0.0 
  intl: ^0.18.0
  grouped_list: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
flutter:
  uses-material-design: true
  assets:
    - assets/images/


